<?php die( 'These aren\'t the droids you\'re looking for...' );

/**
 * Extract of translatable text strings from the lib/pro classes.
 */
_x( 'Select a Place', 'option label', 'wpsso-plm' );
_x( 'Place Schema Type', 'option label', 'wpsso-plm' );
_x( 'Place Alternate Name', 'option label', 'wpsso-plm' );
_x( 'Street Address', 'option label', 'wpsso-plm' );
_x( 'P.O. Box Number', 'option label', 'wpsso-plm' );
_x( 'City', 'option label', 'wpsso-plm' );
_x( 'State / Province', 'option label', 'wpsso-plm' );
_x( 'Zip / Postal Code', 'option label', 'wpsso-plm' );
_x( 'Country', 'option label', 'wpsso-plm' );
_x( 'Telephone', 'option label', 'wpsso-plm' );
_x( 'Place Latitude', 'option label', 'wpsso-plm' );
_x( 'decimal degrees', 'option comment', 'wpsso-plm' );
_x( 'Place Longitude', 'option label', 'wpsso-plm' );
_x( 'decimal degrees', 'option comment', 'wpsso-plm' );
_x( 'Place Altitude', 'option label', 'wpsso-plm' );
_x( 'meters above sea level', 'option comment', 'wpsso-plm' );
_x( 'Open Days / Hours', 'option label', 'wpsso-plm' );
__( 'Opens at', 'wpsso-plm' );
__( 'and closes at', 'wpsso-plm' );
_x( 'Open Dates (Seasonal)', 'option label', 'wpsso-plm' );
__( 'Open from', 'wpsso-plm' );
__( 'through', 'wpsso-plm' );
_x( 'Local Business', 'metabox title', 'wpsso-plm' );
_x( 'Service Radius', 'option label', 'wpsso-plm' );
_x( 'meters from location', 'option comment', 'wpsso-plm' );
_x( 'Currencies Accepted', 'option label', 'wpsso-plm' );
_x( 'Payment Accepted', 'option label', 'wpsso-plm' );
_x( 'Price Range', 'option label', 'wpsso-plm' );
_x( 'Food Establishment', 'metabox title', 'wpsso-plm' );
_x( 'Accepts Reservations', 'option label', 'wpsso-plm' );
_x( 'Serves Cuisine', 'option label', 'wpsso-plm' );
_x( 'Food Menu URL', 'option label', 'wpsso-plm' );
_x( 'Order Action URL(s)', 'option label', 'wpsso-plm' );
_x( 'Place Schema Type', 'option label', 'wpsso-plm' );
_x( 'Place Alternate Name', 'option label', 'wpsso-plm' );
_x( 'Street Address', 'option label', 'wpsso-plm' );
_x( 'P.O. Box Number', 'option label', 'wpsso-plm' );
_x( 'City', 'option label', 'wpsso-plm' );
_x( 'State / Province', 'option label', 'wpsso-plm' );
_x( 'Zip / Postal Code', 'option label', 'wpsso-plm' );
_x( 'Country', 'option label', 'wpsso-plm' );
_x( 'Telephone', 'option label', 'wpsso-plm' );
_x( 'Place Latitude', 'option label', 'wpsso-plm' );
_x( 'decimal degrees', 'option comment', 'wpsso-plm' );
_x( 'Place Longitude', 'option label', 'wpsso-plm' );
_x( 'decimal degrees', 'option comment', 'wpsso-plm' );
_x( 'Place Altitude', 'option label', 'wpsso-plm' );
_x( 'meters above sea level', 'option comment', 'wpsso-plm' );
_x( 'Open Days / Hours', 'option label', 'wpsso-plm' );
__( 'Opens at', 'wpsso-plm' );
__( 'and closes at', 'wpsso-plm' );
_x( 'Open Dates (Seasonal)', 'option label', 'wpsso-plm' );
__( 'Open from', 'wpsso-plm' );
__( 'through', 'wpsso-plm' );
_x( 'Local Business', 'metabox title', 'wpsso-plm' );
_x( 'Service Radius', 'option label', 'wpsso-plm' );
_x( 'meters from location', 'option comment', 'wpsso-plm' );
_x( 'Currencies Accepted', 'option label', 'wpsso-plm' );
_x( 'Payment Accepted', 'option label', 'wpsso-plm' );
_x( 'Price Range', 'option label', 'wpsso-plm' );
_x( 'Food Establishment', 'metabox title', 'wpsso-plm' );
_x( 'Accepts Reservations', 'option label', 'wpsso-plm' );
_x( 'Serves Cuisine', 'option label', 'wpsso-plm' );
_x( 'Food Menu URL', 'option label', 'wpsso-plm' );
_x( 'Order Action URL(s)', 'option label', 'wpsso-plm' );
